### ISSUE TITLE
README.md instructions generate warning message

### ISSUE THREAD

**Issue by andrewjstryker** [shearer/samplesize#2]
Installing this package directly from GitHub, as described in the project's README.md file generates a warning message:

```
> devtools::install_github("samplesize", "shearer")
Downloading GitHub repo shearer/samplesize@master
from URL https://api.github.com/repos/shearer/samplesize/zipball/master
Installing samplesize
'/usr/local/Cellar/r/3.5.1/lib/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/wp/vc3kp9t52c9c_t6b642pf8k80000gp/T/Rtmpt46KUl/devtools8cda3bf63466/shearer-samplesize-5d006c2'  \
  --library='/usr/local/lib/R/3.5/site-library' --install-tests

* installing *source* package ‘samplesize’ ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (samplesize)
Warning message:
Username parameter is deprecated. Please use shearer/samplesize
```

As shown in the warning message, the installation instructions should not use the `username` parameter. Further, usually you don't want to add objects to your namespace if you are only using them once. Here's my suggested fix:

```r
install.packages("devtools") # if not present
devtools::install_github("shearer/samplesize")
```

**Comment by shearer** [comment]
Thank you for the fix of the warning! 
Is corrected now.

**Comment by andrewjstryker** [comment]
Ralph Scherer <notifications@github.com> wrote on 2018-Aug-22:
> Thank you for the fix of the warning! 
> Is corrected now. 
> Not sure what you mean with your namespace suggestion?

Thanks for fixing!

With respect to namespaces, calling `library(devtools)` places all of
the `devtools` objects into a session's namespace. That's overkill when
you only want to use one function in the package.
